/**************************************************************************************
Apex Class Name		:  USIOB_GlobalAssignmentTest
Version          	: 53.0 
Created Date     	: 5th January 2022
                   
* Developer                   Date                   Description
* -------------------------------------------------------------------------------------                 
* Deloitte                   05/01/2022             Original Version   
***************************************************************************************/
@isTest
public class USIOB_GlobalAssignmentTest {

}